from __future__ import annotations

import numpy as np
import numpy.typing as npt

__version__: str

class Expr:
    def __add__(self, other: Expr | float | int) -> Expr: ...
    def __sub__(self, other: Expr | float | int) -> Expr: ...
    def __mul__(self, other: Expr | float | int) -> Expr: ...
    def __truediv__(self, other: Expr | float | int) -> Expr: ...
    def __pow__(self, other: Expr | float | int, modulo: object | None = ...) -> Expr: ...
    def __radd__(self, other: Expr | float | int) -> Expr: ...
    def __rsub__(self, other: Expr | float | int) -> Expr: ...
    def __rmul__(self, other: Expr | float | int) -> Expr: ...
    def __rtruediv__(self, other: Expr | float | int) -> Expr: ...
    def __rpow__(self, other: Expr | float | int, modulo: object | None = ...) -> Expr: ...
    def __gt__(self, other: Expr | float | int) -> Expr: ...
    def __ge__(self, other: Expr | float | int) -> Expr: ...
    def __lt__(self, other: Expr | float | int) -> Expr: ...
    def __le__(self, other: Expr | float | int) -> Expr: ...

class Buffer:
    def numpy(self) -> npt.NDArray[np.float64]: ...
    def scalar(self) -> float: ...

MapArg = Buffer | float | int

class KernelSpec: ...
class MapSpec: ...
class ReduceSpec: ...

class TaskHandle:
    def result(self) -> Buffer: ...
    def is_done(self) -> bool: ...
    def cancel(self) -> bool: ...

class Channel:
    def send(self, buf: Buffer) -> None: ...
    def recv(self) -> Buffer: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...

class RecvCase:
    def __init__(self, channel: Channel) -> None: ...

def py_select(*cases: RecvCase, default: bool = False) -> tuple[int, Buffer | None]: ...

class _KernelModule:
    def arg(self, name: str) -> Expr: ...
    def args(self, *names: str) -> list[Expr]: ...
    def elementwise(self, expr: Expr) -> KernelSpec: ...
    def map(self, spec: KernelSpec, **kwargs: MapArg) -> MapSpec: ...
    def where_(self, cond: Expr, true_val: Expr | float | int, false_val: Expr | float | int) -> Expr: ...
    def sqrt(self, expr: Expr) -> Expr: ...
    def abs(self, expr: Expr) -> Expr: ...
    def log(self, expr: Expr) -> Expr: ...
    def exp(self, expr: Expr) -> Expr: ...
    def log2(self, expr: Expr) -> Expr: ...
    def log10(self, expr: Expr) -> Expr: ...
    def floor(self, expr: Expr) -> Expr: ...
    def ceil(self, expr: Expr) -> Expr: ...
    def round(self, expr: Expr) -> Expr: ...
    def sin(self, expr: Expr) -> Expr: ...
    def cos(self, expr: Expr) -> Expr: ...
    def tan(self, expr: Expr) -> Expr: ...
    def pow(self, base: Expr, exp: Expr) -> Expr: ...
    def atan2(self, y: Expr, x: Expr) -> Expr: ...
    def min(self, left: Expr, right: Expr) -> Expr: ...
    def max(self, left: Expr, right: Expr) -> Expr: ...
    def sum(self, buf: Buffer) -> ReduceSpec: ...
    def mean(self, buf: Buffer) -> ReduceSpec: ...
    def min_reduce(self, buf: Buffer) -> ReduceSpec: ...
    def max_reduce(self, buf: Buffer) -> ReduceSpec: ...

class _RuntimeModule:
    def asarray(self, array: npt.ArrayLike) -> Buffer: ...
    def go(self, spec: MapSpec | ReduceSpec, out: Channel | None = None) -> TaskHandle: ...
    def chan(self, capacity: int) -> Channel: ...
